default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  username: nandini_rathi
  password: 123
  database: blog_demo

  test:
  <<: *default
  # database: sanyam_test

production:
  <<: *default
  database: blog_demo
  username: nandini_rathi
  password: 123